DATA = 'data'
USER_ID = 'user_id'
USERNAME = 'username'
EXISTED = 'existed'
CONTENT = 'content'
NAME = 'name'
BOT_NAME = 'Cheri'
GUEST_NAME = 'Guest'
REQUEST = 'request'
IS_USER = 'is_user'

ENTITY_TAG = ('PERSON', 'ORGANIZATION')
ERROR_THRESHOLD = 0.25
GET_ENTITY_NAME = 'get_entity_name'
PERSON = 'PERSON'
ORGANIZATION = 'ORGANIZATION'
FALSE = 'False'
TRUE = 'True'
WELCOME = 'welcome'
WELCOME_SENT1 = 'Glad to see you come back|What do you want to know this time?'
WELCOME_SENT2 = 'Happy to see you again, %s|What do you want to know this time?'
WELCOME_SENT3 = 'Hi, there. How are you? My name is Cheri|I am an online assistant of Minh|What should I call you by?'

WORDS = 'words'
CLASSES = 'classes'
TRAIN_X = 'train_x'
TRAIN_Y = 'train_y'
INTENTS = 'intents'
TAG = 'tag'
PATTERNS = 'patterns'
RESPONSES = 'responses'
CONTEXT_SET = 'context_set'
CONTEXT_FILTER = 'context_filter'
FUNCTION = 'function'
ALTERNATIVE = 'alternative'
EXTENSIONS = 'extensions'
EMOTION = 'emotion'
TRAINING_DATA = 'training_data'
INTENTS_JSON = 'intents.json'
SOFTMAX = 'softmax'
TF_LOGS = 'tflearn_logs'
MODEL_TF = 'model.tflearn'


